# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CCIP-iOS-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCIP-iOS-Swift
  pod 'RestKit', '~> 0.27'
  pod 'Firebase/DynamicLinks'
  pod 'MTBBarcodeScanner'
  pod 'Kingfisher', '~> 3.10'
  pod 'OneSignal'
  pod 'GoogleAnalytics'

end
