# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CCIP-iOS-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCIP-iOS-Swift
  pod 'Alamofire', '~> 4.4'
  pod 'Firebase/DynamicLinks'
  pod 'RSBarcodes_Swift', '~> 3.0.3'
  pod 'Kingfisher', '~> 3.10'
  pod 'OneSignal'
  pod 'GoogleAnalytics'
  pod 'ObjectMapper', '~> 2.2'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'SwiftKeychainWrapper'

end
